# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        default: "2.0.4"
        description: "Version of the image to publish"
        required: true
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      NACOS_VERSION: ${{ github.event.inputs.version || '2.0.4' }}
    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]NACOS_VERSION=${{env.NACOS_VERSION}}"

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ivyxjc/nacos-server
          flavor: |
            latest=auto

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          context: build
          file: build/Dockerfile
          platforms: ${{ steps.qemu.outputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{steps.version_step.outputs.version}}